# Generated by Django 4.2.3 on 2023-08-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
